### ISSUE TITLE
IOError: Invalid argument

### ISSUE THREAD

**Issue by raivivek** [wbolster/plyvel#135]
Hi!

I was trying to read a database with your package and I'm running into the following issue when trying to print the key/values (for example) in the database.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "plyvel/_plyvel.pyx", line 310, in plyvel._plyvel.DB.get
  File "plyvel/_plyvel.pyx", line 111, in plyvel._plyvel.db_get
  File "plyvel/_plyvel.pyx", line 88, in plyvel._plyvel.raise_for_status
plyvel._plyvel.IOError: b'IO error: db//000065.sst: Invalid argument'
```

I'd greatly appreciate some input/help. Thanks!

**Comment by wbolster** [comment]
fyi, this is a leveldb error, not plyvel specific.

i suspect your database lives on a non-supported filesystem.

please try to reproduce with a minimal example (copy/paste a few lines from the tutorial in the docs, for instance)
